name: Docker Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Create build files
        run: |
          docker run --rm \
          -v $(pwd):/mnt/ -w /mnt/ \
          -t debian:sid bash -c '
          apt update
          apt install build-essential make nasm yasm zlib1g-dev liblzma-dev golang ca-certificates tar gcc-aarch64-linux-gnu -y
          go run build/build.go llvm-mingw
          go run build/build.go
          go run build/build.go --arch arm64
          go run build/build.go --os windows
          go run build/build.go --os windows --arch arm64'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/mp4-remux-linux-amd64
            bin/mp4-remux-linux-arm64
            bin/mp4-remux-windows-amd64.exe
            bin/mp4-remux-windows-arm64.exe
