name: Docker Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v4

    - name: Create build files
      run: |
        docker run --rm \
        -v $(pwd):/mnt/ -w /mnt/ \
        -t debian:sid bash -c '
        apt update
        apt install build-essential git make nasm yasm liblzma-dev liblzma-dev golang mingw-w64 -y
        git config --global --add safe.directory "*"
        go run build/build.go --os linux --arch amd64
        go run build/build.go --os windows --arch amd64 --cc x86_64-w64-mingw32-gcc'

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          mp4-remux
          mp4-remux.exe