name: Docker Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v4

    - name: Create build files
      run: |
        docker run --rm \
        -v $(pwd):/mnt/ -w /mnt/ \
        -t debian:sid bash -c '
        apt update
        apt upgrade -y
        apt install build-essential git make nasm yasm zlib1g-dev liblzma-dev golang mingw-w64 wget tar gcc-aarch64-linux-gnu -y
        git config --global --add safe.directory "*"
        go run build/build.go
        go run build/build.go --arch arm64
        go run build/build.go --os windows

        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20240518/llvm-mingw-20240518-ucrt-ubuntu-20.04-x86_64.tar.xz
        tar -xf llvm-mingw-20240518-ucrt-ubuntu-20.04-x86_64.tar.xz
        mv llvm-mingw-20240518-ucrt-ubuntu-20.04-x86_64/* /usr/local/

        go run build/build.go --os windows --arch arm64'

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          mp4-remux-linux-amd64
          mp4-remux-linux-arm64
          mp4-remux-windows-amd64.exe
          mp4-remux-windows-arm64.exe